/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 06.09.2026 02:01:48

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1488;
#else
constexpr int kTensorArenaSize = 464;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,33 } };
const TfArray<1, float> quant0_scale = { 1, { 0.031123559921979904, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data1[3] = { 118, -183, 1, };
const TfArray<1, int> tensor_dimension1 = { 1, { 3 } };
const TfArray<1, float> quant1_scale = { 1, { 0.00058605108642950654, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[3*16] = { 
  -36, -72, -66, -85, 89, -20, -105, -10, 54, 64, -76, 10, 59, 43, 27, 17, 
  -85, -64, -20, 80, -56, 70, -44, -2, -61, 27, 5, -5, -1, 127, -44, 45, 
  -18, -100, -124, 66, -92, -37, 69, 19, 25, -79, -18, 18, -47, -21, 72, 19, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 3,16 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0064179557375609875, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[16] = { 538, -157, -291, 30, 232, -131, 240, -86, -63, 186, -155, 0, 0, -65, 330, 0, };
const TfArray<1, int> tensor_dimension3 = { 1, { 16 } };
const TfArray<1, float> quant3_scale = { 1, { 0.00029226604965515435, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[16*16] = { 
  46, 32, 127, -37, -21, 28, 3, -46, 29, 33, 30, 90, 25, 12, -115, -13, 
  60, -46, -55, 51, 67, -25, 83, 20, 30, 9, -36, -68, 54, -65, 111, -47, 
  -77, 54, 14, 9, 90, 78, -62, -98, -59, -5, -10, -56, 76, 7, 113, -55, 
  19, 55, -80, -83, 23, 97, 4, -61, 64, 28, -26, 51, 42, 68, 82, -75, 
  47, -88, 69, 73, 44, -108, 35, 74, 68, 19, -76, -17, 65, -32, -115, 5, 
  -17, -69, -1, -15, 15, -16, -2, 57, -63, -89, 19, 39, 54, -61, 23, 0, 
  83, -57, -45, 10, -18, 49, -78, 10, 63, -64, 0, 28, -27, 29, 49, 64, 
  -19, -40, -85, -48, -69, -54, -47, 46, -42, -31, 27, 28, 12, 31, 25, -16, 
  79, -81, 43, 5, -74, -65, 65, -50, -61, -3, 13, 62, 13, -73, 42, 82, 
  -55, -4, 79, 24, 43, -3, -13, 35, 36, -63, -32, -91, 94, -9, 81, 1, 
  -47, 87, 4, 32, -60, 67, -77, -10, 42, -13, 18, -32, 15, -61, 118, -24, 
  0, 60, -15, 69, -70, 53, 61, -60, -38, -6, -82, -36, 4, 22, -67, -68, 
  -30, -16, -4, -74, -5, 8, 44, -32, -27, 0, -10, -65, -54, 40, -62, 76, 
  -73, 42, -13, 41, 104, -66, 73, -85, -60, 16, 70, -62, 88, -52, 114, 43, 
  -74, 64, 67, 66, 47, -36, 6, 57, 77, 49, 88, 41, -4, -69, -101, -63, 
  37, -24, 30, 82, 82, 20, -82, -72, -57, -63, -68, 6, 54, 9, -78, -27, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 16,16 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0050975773483514786, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[16] = { 66, -47, 614, -64, 443, -112, -116, 680, 816, 310, -17, 502, 402, 11, -30, -77, };
const TfArray<1, float> quant5_scale = { 1, { 0.00019117728515993804, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[16*32] = { 
  -8, -9, 47, 48, -27, -15, 7, 68, 5, 20, -2, -27, -54, 0, 98, -85, 12, 41, -11, 22, -67, -24, 46, -15, -17, 29, 74, 61, 75, -39, -12, -77, 
  -72, 15, 18, 77, -7, -72, -42, 60, -21, -32, -33, -13, 89, 92, -5, 69, 105, -46, 77, -45, -41, -56, -1, 1, 30, 35, 88, -9, -69, -39, 85, -39, 
  13, 63, -40, 3, 3, -1, 52, 33, 109, 40, 57, 93, 17, -60, 45, 110, -97, 67, -11, -54, -25, 52, 58, 20, 55, 81, -75, 0, -46, 12, 75, 86, 
  38, -52, 31, -33, 57, -22, -65, 38, 15, -69, -18, 58, 0, -44, -44, 20, -57, 0, -31, -34, 36, -22, 48, 33, 58, -53, 33, -8, -2, -57, -61, -16, 
  19, 31, -31, -28, -65, -33, 51, -2, -40, 26, -32, -23, -30, 69, 23, 0, 66, 104, 57, -18, -65, 83, -25, 37, -44, -15, -45, -9, 41, 59, 84, -24, 
  -94, 4, 67, 66, -18, -89, -67, 85, -68, 20, -23, -47, 83, 82, -103, -31, -9, 39, 86, 54, 5, -9, -51, 56, -9, 66, 39, 1, 31, 23, -29, -75, 
  63, 14, 40, 42, -72, -27, 48, -1, 18, -14, 39, -76, -39, -17, 41, 47, -30, -58, -53, 51, -14, 6, -60, -58, -53, -25, 6, -41, -81, 22, -61, -28, 
  5, 77, -18, -88, -71, 106, 113, 35, 75, 93, 58, 114, 38, 61, 107, 80, -34, 38, -95, -21, 71, 79, 70, 40, -18, 92, -32, -81, 77, -51, 49, 75, 
  18, -103, 61, 72, 7, 6, 100, 81, 36, -24, -59, 78, 82, -5, -5, 113, -26, -44, 47, 62, 12, 104, -22, 9, 18, -54, 82, 25, 41, -71, 69, -6, 
  2, -104, 60, 58, -27, 64, 61, 80, 7, -30, -13, -37, 24, 60, -46, 44, -10, -87, -21, 75, -21, 34, -29, 86, -5, 93, -21, -39, -36, 85, -18, 71, 
  -84, -91, -21, 42, 12, -46, 20, 19, -67, -88, -19, -15, -5, -57, -82, 18, -13, -52, 8, 59, -53, 28, -21, 74, 21, 27, 34, 89, 26, 56, 71, 47, 
  -127, -38, -42, 74, 43, 29, -37, -16, -13, -48, 21, 24, 102, -60, -10, 51, -24, -53, -51, 54, -66, -59, -61, -10, 81, 77, 75, -17, 69, -47, 30, -56, 
  -29, 108, -42, 78, -14, 14, 94, -53, 60, 23, -65, -6, -90, 63, -65, -10, 51, 85, 42, 24, 34, -70, -43, 61, -80, -34, -61, -52, 12, 54, 13, 44, 
  9, -11, -21, -34, -76, 51, -42, -35, 47, 35, -37, 2, -79, -65, -41, -61, -35, 12, 72, -2, 55, -63, -55, 47, -13, 7, 3, -68, 55, -41, 10, -3, 
  60, 61, 96, -1, -7, 37, -54, -69, -17, 74, 72, -23, 3, 34, -16, -70, 116, -47, 47, 106, 13, -103, 3, -45, 99, -21, -4, -63, -105, 109, 22, -60, 
  45, 43, -10, -44, 6, -35, -35, 43, -3, -11, 41, -23, 3, -52, 6, 25, -47, -65, 47, -56, -77, -14, 16, 29, 32, -39, 27, -48, 7, 69, -19, 31, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 16,32 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0043978579342365265, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data7[32] = { 88, 287, -341, 610, -315, 431, 654, 676, 582, 377, -61, 782, 308, 27, 119, 1036, -142, 349, -81, 148, -26, 834, -91, 663, 610, 694, 279, -84, 248, 127, 1351, 511, };
const TfArray<1, int> tensor_dimension7 = { 1, { 32 } };
const TfArray<1, float> quant7_scale = { 1, { 0.0001711636723484844, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data8[32*33] = { 
  -21, -84, -72, 59, -33, -4, 14, 13, 13, 3, 13, -5, 6, -57, 40, -42, -51, 59, -17, 56, 52, 87, -25, 5, -33, 31, 33, -22, -5, -12, -35, 51, 43, 
  -49, -70, -20, 49, -53, 7, 25, -2, 10, -12, 74, 18, 31, 37, 19, 55, -67, 27, 16, 6, 82, 2, -41, 78, 3, -21, 39, -19, 37, 47, 19, 32, 12, 
  80, -56, 18, 34, 46, 30, 12, 9, -17, 64, 53, 35, 37, 13, -80, 28, -41, -18, -30, -46, 63, 60, 24, 18, -47, 24, 32, 1, 10, 1, 19, -36, 44, 
  16, 60, 114, 0, 89, 37, 14, 59, 63, 26, 2, 56, 56, 36, 66, 52, 11, 7, 55, -16, 75, 11, -32, -14, 34, -18, -29, 56, 4, 26, 58, 58, 3, 
  34, -45, -20, 16, -42, -26, -48, 23, -46, -29, 21, -34, 2, -21, -45, -26, -18, -5, -52, -33, 44, -35, -25, 29, -56, -5, -19, -21, 45, 40, -20, -31, -63, 
  -76, 27, -69, 4, -67, -20, 3, -55, -26, -58, -97, -18, -32, -63, -13, 8, -44, -9, -104, -4, -18, -19, 29, -13, 54, 40, 8, 14, -19, 9, 4, 39, 66, 
  -33, -2, -127, -23, -54, -22, -8, -1, -16, -118, -87, -43, 24, -96, -41, -49, -44, -6, -88, 76, -36, -38, 68, -4, 61, 4, 38, -13, -11, -1, 8, -31, -14, 
  71, 45, 33, 41, 51, 8, 55, 41, 27, 40, -3, -77, 9, 16, -48, -47, 18, 7, -10, -54, -37, -87, 9, -34, 36, -15, -37, -21, -28, -30, -8, 23, 60, 
  13, 10, -42, -14, -24, -27, -17, -64, -36, -37, 5, -20, -35, 37, -2, 14, -4, -21, -53, 41, -16, -33, 52, -13, -9, -31, -44, -26, -33, 53, -11, 11, -26, 
  -89, 41, -64, -55, -47, -29, -33, 14, 11, -81, -48, 57, -38, -80, -46, 55, -7, 71, 60, 28, -28, 64, 24, -47, 48, 21, 82, -19, -30, 16, 52, -37, 35, 
  51, -49, 9, -55, -37, -5, -43, -56, 30, -42, -2, -1, -45, 9, -32, 43, 50, -47, 12, 24, -45, -12, -38, 21, -44, 19, -53, 34, -49, 54, 31, 26, 22, 
  -63, -21, -115, 7, -4, 38, 40, -2, -13, -50, -69, -22, 34, -94, 41, -26, -59, -56, -64, -78, -59, -8, 34, 19, 23, 31, 19, -58, -26, -33, -30, -11, 17, 
  -6, 25, 26, 39, -8, -42, -25, -39, -43, 44, -2, -17, -25, 53, 28, 15, 53, 22, -74, -32, -87, -65, -20, 71, -28, 10, -45, 48, 14, 45, 2, 48, -3, 
  39, -12, 59, 36, 18, -5, -36, 67, 16, 5, -22, 30, -56, 74, -13, 16, 12, 51, 59, 97, 8, 58, 57, 50, -18, 61, -32, -11, -39, -31, 62, 45, -20, 
  25, -6, -77, -8, 46, 17, -23, -25, -56, 14, -67, 46, 17, 6, -71, -60, 77, 2, 36, 32, -32, -51, 46, -60, -41, -42, 22, 52, 52, -41, -55, -29, -53, 
  -28, 46, -52, -31, 54, 22, -21, 25, 20, -45, -22, -81, 46, -56, -11, -29, -3, -52, -26, -29, -74, -68, 49, 27, 64, 41, 74, 34, -29, -16, -18, -4, 44, 
  44, 21, 57, -36, 2, 27, 23, -28, 68, 72, -2, 114, 32, 92, -3, 74, 41, 3, 41, 25, 110, 12, -32, -12, 40, 16, -44, -32, 1, 40, 7, -63, 30, 
  -15, -35, -22, 65, 51, 20, -47, 11, 13, -4, -30, 23, -21, -70, -76, -82, -14, -25, -12, -7, -10, 47, -33, 18, 56, -20, -24, 40, -35, -31, -26, 35, 15, 
  -19, -5, 49, -40, 53, 7, -18, -21, 84, 21, 34, 41, 46, 74, 39, -2, -49, -14, 2, -34, -14, 84, -45, 17, 63, -44, 16, 26, 49, -22, -34, -31, 5, 
  54, 55, 54, 24, 52, 48, 53, 41, 57, -9, 43, 97, -35, 112, 12, 33, 46, 73, 20, 84, 104, 44, 60, -19, -9, -19, 42, 59, -20, -39, 10, -37, -3, 
  -8, 0, -44, -14, -33, -44, -13, -35, 26, -24, 39, 45, -7, -32, 22, 34, 3, -51, 39, -52, -46, 33, -18, -48, 4, -6, -45, 30, -45, -8, -40, 36, -43, 
  -51, -3, -70, 8, -5, 54, 7, -64, 8, 0, -13, -87, -3, -81, 61, -1, -9, -38, -84, -64, -18, -51, 59, -35, 23, -22, 66, 14, -45, 33, 10, 47, 29, 
  -11, -33, -37, 1, 6, -6, 51, -2, -42, -35, 29, 27, -28, 42, 40, -17, -10, 41, -41, -46, -43, -12, -52, -40, 12, 25, -56, -27, -9, -55, -17, -14, -50, 
  24, -31, 42, -10, -13, -38, -2, -32, -18, 9, -42, 6, 59, -60, 12, 8, -16, -68, 24, -38, -50, -30, 10, 24, 48, 45, 20, 16, -51, 40, 43, 43, 6, 
  53, 4, 7, 26, -19, 37, -58, 18, -20, 63, 46, 23, 62, 73, 39, -1, 16, 32, 4, -20, -52, -50, -29, 28, -16, 27, 5, -52, -35, 43, 60, 27, 68, 
  33, 72, -32, 18, 57, 10, -36, -72, 8, -61, -9, 16, -1, 27, -9, -48, -19, -32, -38, -101, -76, -40, 57, 36, 0, 30, 58, -22, 29, 36, 53, -1, -42, 
  26, 42, 16, 33, 54, 13, -62, -6, -44, -7, -24, -29, -55, 64, 51, -11, 16, 22, -28, -71, -26, 14, -6, 55, -41, 20, -17, 11, -16, -31, 1, 17, -9, 
  -51, -14, -26, -3, 21, 50, -52, 31, 16, 40, -34, -36, -25, -29, 47, 58, -36, 58, -18, -38, -76, -12, -41, 20, 45, 7, 5, -40, -13, -19, 24, 15, 6, 
  27, 64, 11, 26, -33, 17, 25, 0, -63, -8, -56, -62, 26, -44, -20, 10, 16, 33, -3, -42, -54, -15, 50, 6, 5, -47, -11, -66, 34, -50, 17, -37, -56, 
  50, -9, 68, 10, 46, -50, 41, 70, 44, 14, 65, 15, -44, 33, 45, 75, 26, 18, 32, 12, 51, 35, 31, 29, -38, 38, 44, 45, -28, 63, -34, -7, -26, 
  14, -1, 0, 3, 22, 38, 31, -61, 10, -37, -6, 31, 73, -22, 65, -4, 49, 49, 29, -22, -19, -25, -3, -2, 20, 13, 2, -3, 56, 45, 61, 31, 59, 
  -32, 40, -107, 10, -27, -12, 44, -43, -65, -63, -58, -5, -41, -90, -49, -18, 26, -33, -42, -24, -73, -19, 14, 23, 5, 44, 62, 35, 0, 29, 2, 13, 51, 
};
const TfArray<2, int> tensor_dimension8 = { 2, { 32,33 } };
const TfArray<1, float> quant8_scale = { 1, { 0.0054994886741042137, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,32 } };
const TfArray<1, float> quant9_scale = { 1, { 0.04347054660320282, } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<2, int> tensor_dimension10 = { 2, { 1,16 } };
const TfArray<1, float> quant10_scale = { 1, { 0.057334303855895996, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<1, float> quant11_scale = { 1, { 0.091314293444156647, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<2, int> tensor_dimension12 = { 2, { 1,3 } };
const TfArray<1, float> quant12_scale = { 1, { 0.15893758833408356, } };
const TfArray<1, int> quant12_zero = { 1, { 46 } };
const TfLiteAffineQuantization quant12 = { (TfLiteFloatArray*)&quant12_scale, (TfLiteIntArray*)&quant12_zero, 0 };
const TfArray<1, float> quant13_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,8,7 } };
const TfArray<1, int> outputs0 = { 1, { 9 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 9,6,5 } };
const TfArray<1, int> outputs1 = { 1, { 10 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 10,4,3 } };
const TfArray<1, int> outputs2 = { 1, { 11 } };
const TfLiteFullyConnectedParams opdata3 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs3 = { 3, { 11,2,1 } };
const TfArray<1, int> outputs3 = { 1, { 12 } };
const TfLiteSoftmaxParams opdata4 = { 1 };
const TfArray<1, int> inputs4 = { 1, { 12 } };
const TfArray<1, int> outputs4 = { 1, { 13 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 33, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 48, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 256, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension3, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 512, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 128, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 1056, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 48), (TfLiteIntArray*)&g0::tensor_dimension9, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension10, 16, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension10, 16, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension12, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension12, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[5] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[5] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 14, };
const size_t tflNodes_subgraph_index[] = {0, 5, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  13, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1106290_7_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 14;
  for (size_t i = 0; i < 14; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1106290_7_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1106290_7_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1106290_7_invoke() {
  for (size_t i = 0; i < 5; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1106290_7_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
